### ISSUE TITLE
Sorting by "Feed type" only affects displayed rows

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#421]
In the front end, when I click on "Feed type", only the currently displayed rows are sorted. Is this the intended behaviour? Because I assumed that all resulting IOCs would be sorted, as this is the behaviour of sorting by every other column.

The reason for this is, that sorting by "feed_type" is not done on a database level but just before the HTTP response is returned. But because of pagination, at this point the list of IOCs does only contain the IOCs for the requested page.

**Comment by drosetti** [comment]
Hi can you specify what part of the frontend ? A screenshot will be appreciated.

**Comment by regulartim** [comment]
Here:
![grafik](https://github.com/user-attachments/assets/55e2fee6-14ec-49fb-8d3c-9368f4a4a09c)

I realised that when I changed some backend code today for #419 .

**Comment by drosetti** [comment]
No I think it's a bug, I assign the issue to you.

Edit: Obviously if you only wanted to report the bug and not work on it let me know :smile:

**Comment by regulartim** [comment]
No, I'm happy to have a look. :) But I would like to prioritise other things first. To be honest, I'm not sure if we should fix this at all or if it makes more sense to remove the functionality (sorting by feed type) altogether.

**Comment by drosetti** [comment]
Ok don't worry, I'll ping next weeks and you will tell me if you need more time or what do you prefer. Talking about the feature we can think about a solution together, so write what do you think about it and what you suggest

**Comment by regulartim** [comment]
I have thought about this a few times. We are working with a paginated query set here. If we sort at this point, we are only sorting the contents of the current page, which is clearly not what we want. What we should be doing is sorting at the database level (as we do for all the other properties, e.g. Last Seen). But the database, as it is now, has no concept of "feed type". I see two options:
1. Remove the option to sort by feed type altogether
2. Change our IOC model in some way to allow the database to do the sorting. This is not trivial as a single IOC can have one of many feed types depending on the request. For example, if an IOC has been seen by both Cowrie and Adbhoney, it will appear in the Cowrie feed with feed type "Cowrie", in the Adbhoney feed with feed type "Adbhoney" and in the All feed with one of the two feed types (currently it would be "Cowrie"). 

I would prefer option 1. Option 2 would be a lot of work for little benefit.

**Comment by drosetti** [comment]
I agree with you that changing the IOC model is too much effort. What do you thin about ordering by multiple fields, Django allows to do it

**Comment by regulartim** [comment]
Could you please explain how ordering by multiple fields would solve the problem? I'm sorry, I don't understand.

**Comment by drosetti** [comment]
It's explained in the django docs: https://docs.djangoproject.com/en/5.1/ref/models/querysets/#order-by.
This should solve the problem.

**Comment by regulartim** [comment]
I'm sorry, but I still do not see how this solves the problem. If I understand it correctly `order_by()` works on the database level but, as I said, the database has no concept of "feed type". Could you please further elaborate your idea?

**Comment by mlodic** [comment]
I tried to follow the thread here. The GUI is very minimal and limited and has been made with the intent to make the project "more serious" in the eyes of potential users. I agree that there are a lot of possible improvements to be made here, in particular if we consider the changes that you have made during last months.

Having said that, I try to summarize the problems. Lmk if anything misses here:

- [ ] in the GUI "Feed type" is just a single element while it should support all the feeds that reported a specific IP address. In my opinion, we should swap IP addresses and Feed types to prioritize IP addresses as a column and then allow multiple feed types there. Related issue https://github.com/intelowlproject/GreedyBear/issues/289
- [ ] The GUI ordering of the "Feed type" is wrong. Yes but it's not too bad in my opinion. Considering the complex changes we should do in the DB, I would leave it as is.
- [ ] One really useful thing that we could add is the GUI section of the "enrichment" API. I would like to have a little form with just an IP address as the single input and as result the data related to that IP address in the DB, if present. (with authentication required). ref: https://github.com/intelowlproject/GreedyBear/issues/436

Then there's all the stuff regarding the advanced feeds that you created. @regulartim if you want to propose some related GUI additional work, feel free to open an issue about it. If you don't manage to solve that issue, that could be a possible future task for a future contributor so I would really appreciate to have those ideas here. During these days, we have been also proposing some projects for the Google Summer of Code, so this stuff could be something that we could propose to a student. ty

**Comment by regulartim** [comment]
> if you want to propose some related GUI additional work, feel free to open an issue about it. 

Will do that! :) 

> If you don't manage to solve that issue, that could be a possible future task for a future contributor

I have basic knowledge of JS but never worked with react code, so I assume that working on the frontend will take me a lot of time which I currently don't have. Maybe  I'll take a look in summer. 

I would suggest leaving this issue open, either for me or for a future contributor.

**Comment by Vrohs** [comment]
I'll be looking into this.

**Comment by regulartim** [comment]
Hey @Vrohs ! Before you can contribute here, please read and follow our [contribution guidelines](https://intelowlproject.github.io/docs/GreedyBear/Contribute/). For example they state that "Before starting to work on an issue, you need to get the approval of one of the maintainers. Therefore please ask to be assigned to an issue.". 

Also, the PR that you raised also does not follow the guidelines and does not use our PR template.

I will assign you to this issue, but please make sure you thoroughly read and follow the guidelines in the future.

**Comment by Vrohs** [comment]
Thanks @regulartim, I'll keep that in mind.

**Comment by regulartim** [comment]
I am sorry @Vrohs  but I will unassign you due to inactivity.

**Comment by armoredvortex** [comment]
Hi, can i get assigned to this?

**Comment by regulartim** [comment]
Hi @armoredvortex !

This is what I wrote in the last PR tackling this issue:

> When the issue was opened, "feed_type" was a single value, as you can see on the screenshot. Since then, a lot happened in this project, including "feed_type" being a list. What do you think, does it even make sense to sort by a list?

What do you think?

**Comment by armoredvortex** [comment]
@regulartim you make a good point.
sorting by a list would be ambigous. And since we can already filter by feed type, I believe that already solves the user need.
So we should probably just disable the sorting indicator on that field.

**Comment by armoredvortex** [comment]
While on the topic, I noticed that you can only select one option in the Feed type dropdown.
Would it make more sense to be able to select multiple entries at a time and display their intersection?

**Comment by regulartim** [comment]
I agree and like you suggestion. You can make both changes in one PR if you want.
